#!/bin/sh -x
#PJM -L  "freq=2200"
#PJM -L  "node=8x12x8"
#PJM -L  "rscgrp=large,eco_state=2"
#PJM --mpi "shape=8x12x8"
#PJM -L  "elapse=00:05:00"
#PJM --mpi "max-proc-per-node=4"
#PJM -s
#

# 8x12x8=768
# 12x15x12=2160
# 16x24x16=6144
# 24x32x24=18432
# 32x36x32=36864
# 36x36x36=46656

export OMP_NUM_THREADS=12

export COMM_OMP_FLAG=0
export COMM_BORDER_ONE_FLAG=1
export COMM_PIGGY_FLAG=1
export THREAD_POOL_FLAG=1
export COMM_DEBUG_FLAG=0

mpiexec  ./lmp_execute  -in ./in.threadpool.lj.60k                           # Execute a.out
# mpiexec  ./lmp_omp  -in ./in.omp.lj                           # Execute a.out