#!/bin/sh -x
#PJM -L  "freq=2200"
#PJM -L  "node=8x12x8"
#PJM -L  "rscgrp=large,eco_state=2"
#PJM --mpi "shape=8x12x8"
#PJM -L  "elapse=00:05:00"
#PJM --mpi "max-proc-per-node=4"
#PJM -s
#

export OMP_NUM_THREADS=12

export COMM_OMP_FLAG=0
export COMM_BORDER_ONE_FLAG=1
export COMM_PIGGY_FLAG=1
export THREAD_POOL_FLAG=1
export COMM_DEBUG_FLAG=0

mpiexec  ./lmp_execute  -in ./in.eam.threadpool.60k                   # Execute a.out